# Generated by Django 4.1.2 on 2023-11-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_taskassign',
            name='subtask',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='project_taskassign',
            name='task',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='project_taskassign',
            name='tl_description',
            field=models.TextField(default=None),
        ),
    ]
