# Generated by Django 4.1.2 on 2023-11-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_alter_project_taskassign_subtask_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_taskassign',
            name='description',
            field=models.TextField(blank=True, default='None', null=True),
        ),
        migrations.AlterField(
            model_name='project_taskassign',
            name='subtask',
            field=models.TextField(blank=True, default='None', null=True),
        ),
        migrations.AlterField(
            model_name='project_taskassign',
            name='task',
            field=models.TextField(blank=True, default='None', null=True),
        ),
        migrations.AlterField(
            model_name='project_taskassign',
            name='tl_description',
            field=models.TextField(blank=True, default='None', null=True),
        ),
    ]
